apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
    - name: myapp
      image: llzzrrr/myapp:v1
      ports:
        - name: myapp
          containerPort: 8080