apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
    - name: myapp
      image: llzzrrr/myapp:v3
      ports:
        - name: myapp
          containerPort: 8080
      readinessProbe:
        httpGet:
          path: /heartbeat
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /heartbeat
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 5
